import type { NextPage } from 'next'
import Head from 'next/head'
import HelloWorld from '../components/HelloWorld/HelloWorld'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <meta property="og:title" content="Next Website"></meta>
        <meta property="og:type" content="website"></meta>
        <meta property="og:image" content="#"></meta>
        <meta property="og:url" content={`${process.env.NEXT_PUBLIC_BASE_URL}/`}></meta> 

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HelloWorld />
      </main>
    </div>
  )
}

export default Home
